# BIBLIOTEQUES ET LIBRAIRIES NECESSAIRES

#### This notebook contains some Hackerrank problems that I solved for fun. I hope this will help you prepare for your interview. The solution is not optimized):

# Library

In [6]:
import math
import os
import random
import re
import sys

# Variables

# Army Game

#### Subject

<img src="./HackerRankFile/armyGame1.png" alt="Problem_1" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/armyGame0.png" alt="Problem_0" style="height: 900px; width:900px;"/>

#### Solution

In [ ]:
#
# Complete the 'gameWithCells' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER m
#
def gameWithCells(n, m):
    """
        Solution
    """
    # Write your code here
    if((n%2 == 1) and (m%2 == 1) and (n>1) and (m>1)):
        return int(((n-1)*(m-1))/4)+int(m/2)+(m%2)+int(n/2)
    if((n == 1) and (m%2 == 1) and(m>1)):
        return int(m/2)+1
    if((m == 1) and (n%2 == 1) and(n>1)):
        return int(n/2)+1
    if(n%2 == 1):
        return int(((n-1)*m)/4)+int(m/2)+(m%2)
    if(m%2 == 1):
        return int((n*(m-1))/4)+int(n/2)+(n%2)
    return max(int((n*m)/4),1)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    result = gameWithCells(n, m)

    fptr.write(str(result) + '\n')

    fptr.close()

# Fizz Buzz

#### Subject

<img src="./HackerRankFile/fizzBuzz0.png" alt="Problem_1" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/fizzBuzz1.png" alt="Problem_0" style="height: 900px; width:900px;"/>

#### Solution

In [ ]:
to do

# Twins

#### Subject

<img src="./HackerRankFile/twins0.png" alt="Problem_0" style="height: 900px; width:900px;"/>

#### Solution

In [ ]:
#!/bin/python3
import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER m
#

    
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n > 2 and n % 2 == 0:
        return False
 
    max_div = math.floor(math.sqrt(n))
    for i in range(3, 1 + max_div, 2):
        if n % i == 0:
            return False
    return True

    
def SieveOfEratosthenes(minimum_primary, n):
    prime = [True for i in range(n+1)]
    list_primafry_number = []
    p = 2
    while(p * p <= n):
        if (prime[p] == True):
            for i in range(p * p, n + 1, p):
                prime[i] = False
        p += 1
 
    for p in range(max(minimum_primary,2), n):
        if prime[p]:
            list_primafry_number.append(p)
    return list_primafry_number

    
    
def solve(n, m):
    # Write your code here
    number_of_tiws = 0
    list_values_all = SieveOfEratosthenes(max(n,2), m+1) # sorted(list_values_all)

    for first_value in list_values_all:
        if(first_value+2 in list_values_all):
            number_of_tiws+=1
    return number_of_tiws
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    result = solve(n, m)

    fptr.write(str(result) + '\n')

    fptr.close()

# Correlation and Regression Lines - A Quick Recap #1

#### Subject

<img src="./HackerRankFile/CorrelationAndRegressionLines.png" alt="Correlation And Regression Lines" style="height: 700px; width:900px;"/>

#### Solution

In [ ]:
import math


def mean_list(list_to_mean):
    """
    """
    return sum(list_to_mean)/len(list_to_mean)


def different_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]-second_vector[one_values])
    return result_diff


def product_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]*second_vector[one_values])
    return result_diff



def karl_pearson_correlation(first_vector, second_vector):
    """
        uses this function to comput Karl Pearson Correlation
    """

    tamp1 = sum(product_between_two_vector(different_between_two_vector(first_vector,len(first_vector)*[mean_list(first_vector)]), different_between_two_vector(second_vector,len(second_vector)*[mean_list(second_vector)])))
    tampon_values_first = different_between_two_vector(first_vector,len(first_vector)*[mean_list(first_vector)])
    tampon_values_second = different_between_two_vector(second_vector,len(second_vector)*[mean_list(second_vector)])
    tamp2 = math.sqrt(sum(product_between_two_vector(tampon_values_first,tampon_values_first))*sum(product_between_two_vector(tampon_values_second,tampon_values_second)))
    if (tamp2 == 0.0):
        if (first_vector == second_vector):
            return 1.0
        else:
            return 0.0

    return tamp1/tamp2

first_vector = [15, 12, 8, 8, 7, 7, 7, 6, 5, 3]
second_vector = [10, 25, 17, 11, 13, 17, 20, 13, 9, 15]
print('%.3f' % round(karl_pearson_correlation(first_vector, second_vector),3))

# Day 6: Multiple Linear Regression: Predicting House Prices

#### Subject

<img src="./HackerRankFile/Day6MultipleLinearRegressionPredictingHousePrices_0.png" alt="Day 6: Multiple Linear Regression: Predicting House Prices 0" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/Day6MultipleLinearRegressionPredictingHousePrices_1.png" alt="Day 6: Multiple Linear Regression: Predicting House Prices 1" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/Day6MultipleLinearRegressionPredictingHousePrices_2.png" alt="Day 6: Multiple Linear Regression: Predicting House Prices 2" style="height: 900px; width:900px;"/>

#### Solution

In [ ]:
to do

# Correlation and Regression Lines - A Quick Recap #2

#### Subject

<img src="./HackerRankFile/CorrelationRegressionLinesAQuickRecap.png" alt="Correlation Regression Lines A Quick Recap" style="height: 400px; width:900px;"/>

#### Solution

In [142]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import math

def mean_list(list_to_mean):
    """
    """
    return sum(list_to_mean)/len(list_to_mean)

def different_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]-second_vector[one_values])
    return result_diff


def product_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]*second_vector[one_values])
    return result_diff

    
def compute_slope_regression(X, Y):
    """
    """
    
    #slope = 1
    mean_x = mean_list(X)
    mean_y = mean_list(Y)
    return sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(Y, len(Y)*[mean_y])))/sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(X, len(X)*[mean_x])))    

    
physics_scores = [15, 12, 8, 8, 7, 7, 7, 6, 5, 3]
history_scores = [10, 25, 17, 11, 13, 17, 20, 13, 9, 15]
print('%.3f' % round(compute_slope_regression(physics_scores, history_scores),3))

0.208


# Camel Case 4

#### Subject

<img src="./HackerRankFile/CamelCase40.png" alt="Camel Case 4 0" style="height: 900px; width:1000px;"/>
<img src="./HackerRankFile/CamelCase41.png" alt="Camel Case 4 1" style="height: 400px; width:900px;"/>

#### Solution

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re
import os
 


def camel_case_four(input_string):
    """
    """
    
    result_string = ""
    split_input_result = input_string.split(";")
    if(split_input_result[0] == "S"):
        if(split_input_result[1] == "C"):
            result_split_regex = re.findall('[A-Z][^A-Z]*', split_input_result[2])
            #result_string = result_split_regex[0].lower()+" "+result_split_regex[1].lower()
            result_string = result_split_regex[0].lower()
            for one_result in range(1, len(result_split_regex)):
                result_string += " "+result_split_regex[one_result].lower()
        if(split_input_result[1] == "M"):
            result_split_regex = re.split('(?=[A-Z])', split_input_result[2])
            result_string = result_split_regex[0].lower()
            for one_result in range(1, len(result_split_regex)):
                result_string += " "+result_split_regex[one_result].lower()
            result_string = result_string[:-2].lower()
        if(split_input_result[1] == "V"):
            result_split_regex = re.split('(?=[A-Z])', split_input_result[2])
            result_string = result_split_regex[0].lower()
            for one_result in range(1, len(result_split_regex)):
                result_string += " "+result_split_regex[one_result].lower()
            
    if(split_input_result[0] == "C"):
        result_split_regex = split_input_result[2].split(" ")
        if(split_input_result[1] == "C"):
            for one_result in result_split_regex:
                result_string += one_result[0].upper()+one_result[1:].lower()
        if(split_input_result[1] == "M"):
            result_string = result_split_regex[0].lower()
            for one_result in range(1, len(result_split_regex)):
                result_string += result_split_regex[one_result][0].upper()+result_split_regex[one_result][1:]
            result_string +="()"
        if(split_input_result[1] == "V"):
            result_string = result_split_regex[0].lower()
            for one_result in range(1, len(result_split_regex)):
                result_string += result_split_regex[one_result][0].upper()+result_split_regex[one_result][1:]
    return result_string

    
fptr = open(os.environ['OUTPUT_PATH'], 'w')
while True:
    try:
        first_multiple_input = input().rstrip().split()
    except:
        break
    n = " ".join(first_multiple_input)
    result = camel_case_four(n)
    fptr.write(str(result) + '\n')
fptr.close()

# Divisible Sum Pairs

#### Subject

<img src="./HackerRankFile/DivisibleSumPairs0.png" alt="Divisible Sum Pairs" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/DivisibleSumPairs1.png" alt="Divisible Sum Pairs" style="height: 400px; width:900px;"/>

#### Solution

In [ ]:
def divisibleSumPairs(n, k, ar):
    # Write your code here
    number_of_pair = 0
    
    for first_el in range(n-1):
        for second_el in range(first_el+1, n):
            if((ar[first_el]+ar[second_el])%k == 0):
                number_of_pair+=1
    return number_of_pair

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()


# Correlation and Regression Lines - A quick recap #3

#### Subject

<img src="./HackerRankFile/CorrelationAndRegressionLinesAquickrecap30.png" alt="Correlation and Regression Lines - A quick recap #3" style="height: 400px; width:900px;"/>

#### Solution

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import math

def mean_list(list_to_mean):
    """
    """
    return sum(list_to_mean)/len(list_to_mean)

def different_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]-second_vector[one_values])
    return result_diff


def product_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]*second_vector[one_values])
    return result_diff

    
def compute_coef_regression(X, Y):
    """
        Y = A+BX
    """
    
    mean_x = mean_list(X)
    mean_y = mean_list(Y)
    
    cov_X_Y = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(Y, len(Y)*[mean_y])))
    var_X = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(X, len(X)*[mean_x])))
    
    B = cov_X_Y/var_X
    A = mean_y- B*mean_x
    return A, B    


physics_scores = [15, 12, 8, 8, 7, 7, 7, 6, 5, 3]
history_scores = [10, 25, 17, 11, 13, 17, 20, 13, 9, 15]
A, B = compute_coef_regression(physics_scores, history_scores)
print('%.3f' % round(A+B*10,3))

# Correlation and Regression Lines - A Quick Recap #4

#### Subject

<img src="./HackerRankFile/CorrelationandRegressionLinesAQuickRecap4_0.png" alt="Correlation and Regression Lines - A Quick Recap #4" style="height: 400px; width:900px;"/>

#### Solution

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
print(round((107+9*7)/20,1))

# Day 5: Computing the Correlation

#### Subject

<img src="./HackerRankFile/Day5ComputingTheCorrelation0.png" alt="Day 5: Computing the Correlation 0" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/Day5ComputingTheCorrelation1.png" alt="Day 5: Computing the Correlation 1" style="height: 900px; width:900px;"/>
<img src="./HackerRankFile/Day5ComputingTheCorrelation2.png" alt="Day 5: Computing the Correlation 2" style="height: 200px; width:900px;"/>

#### Solution

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# Processing Data 
import os
import math

input_data_all = """73  72  76
48  67  76
95  92  95
95  95  96
33  59  79
47  58  74
98  95  97
91  94  97
95  84  90
93  83  90
70  70  78
85  79  91
33  67  76
47  73  90
95  87  95
84  86  95
43  63  75
95  92  100
54  80  87
72  76  90"""
input_data_all = input_data_all.split("\n")

M = []
P = []
C = []
for one_element in input_data_all:
    split_element = one_element.split(" ")
    M.append(int(split_element[0]))
    P.append(int(split_element[2]))
    C.append(int(split_element[4]))
    

def mean_list(list_to_mean):
    """
    """
    return sum(list_to_mean)/len(list_to_mean)

    
def different_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]-second_vector[one_values])
    return result_diff


def product_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]*second_vector[one_values])
    return result_diff

    
def compute_correlation(X, Y):
    """
    """
    
    mean_x = mean_list(X)
    mean_y = mean_list(Y)
    
    cov_X_Y = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(Y, len(Y)*[mean_y])))
    var_X = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(X, len(X)*[mean_x])))
    var_Y = sum(product_between_two_vector(different_between_two_vector(Y, len(Y)*[mean_y]), different_between_two_vector(Y, len(X)*[mean_y])))
    return cov_X_Y/math.sqrt(var_X*var_Y)

print('%.2f' % round(compute_correlation(M, P),2))
print('%.2f' % round(compute_correlation(P, C),2))
print('%.2f' % round(compute_correlation(M, C),2))

# Document Classification

#### Subject

<img src="./HackerRankFile/DocumentClassification0.png" alt="Document Classification" style="height: 900px; width:900px;"/>

#### Solution

In [1]:
import warnings
import pandas as pd
from nltk.corpus import stopwords
from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, multilabel_confusion_matrix, classification_report

In [2]:
warnings.filterwarnings('ignore')

###### Import Data

In [3]:
trainingdata_pandas = pd.read_csv("HackerRankFile/trainingdata.txt", sep="\n")

###### Extract Labeland Text

In [4]:
trainingdata_pandas['Document_Containt'] = trainingdata_pandas.apply(lambda row: row["5485"][2:], axis = 1)
trainingdata_pandas["Label_Document"] = trainingdata_pandas.apply(lambda row: row["5485"][0:1], axis = 1)
del trainingdata_pandas["5485"]
trainingdata_pandas.head(5)

Document_Containt Label_Document
0  champion products ch approves stock split cham...              1
1  computer terminal systems cpml completes sale ...              2
2  cobanco inc cbco year net shr cts vs dlrs net ...              1
3  am international inc am nd qtr jan oper shr lo...              1
4  brown forman inc bfd th qtr net shr one dlr vs...              1

###### Split Data Training and Testing

In [5]:
X_train, X_val, y_train, y_val = train_test_split(trainingdata_pandas["Document_Containt"],
                                                  trainingdata_pandas["Label_Document"],
                                                  test_size=0.20, random_state=42)

###### Support Vector Classification OneVsRestClassifier Tdidf

In [6]:
svc_pipeline = Pipeline([('tfidf', TfidfVectorizer(stop_words=stopwords.words('english'), ngram_range=(1, 1))),
                       ('nb_model', OneVsRestClassifier(SVC()))])

In [7]:
svc_pipeline.fit(X_train.values, y_train.values)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=['i', 'me', 'my', 'myself', 'we',
                                             'our', 'ours', 'ourselves', 'you...
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('nb_model',
                 OneVsRestClassifier(estimator=SVC(C=1.0, break_ties=False,
                              

In [8]:
svc_prediction_result = svc_pipeline.predict(X_val.values)

In [9]:
print('accuracy: ', accuracy_score(y_val.values, svc_prediction_result))
print("f1 Score weighted : ",f1_score(y_val.values, svc_prediction_result, average='weighted'))
print("f1 Score micro : ",f1_score(y_val.values, svc_prediction_result, average='micro'))
print("f1 Score macro : ",f1_score(y_val.values, svc_prediction_result, average='macro'))

print('confusion matrices: ')
print(multilabel_confusion_matrix(y_val.values, svc_prediction_result))
print('classification_report: ')
print(classification_report(y_val.values, svc_prediction_result))

accuracy:  0.9608021877848678
f1 Score weighted :  0.9604545770912919
f1 Score micro :  0.9608021877848678
f1 Score macro :  0.9208470294427842
confusion matrices: 
[[[ 535    6]
  [  15  541]]

 [[ 747   27]
  [   3  320]]

 [[1039    4]
  [   1   53]]

 [[1077    0]
  [   4   16]]

 [[1088    0]
  [   2    7]]

 [[1044    0]
  [   5   48]]

 [[1057    2]
  [   5   33]]

 [[1049    4]
  [   8   36]]]
classification_report: 
              precision    recall  f1-score   support

           1       0.99      0.97      0.98       556
           2       0.92      0.99      0.96       323
           3       0.93      0.98      0.95        54
           4       1.00      0.80      0.89        20
           5       1.00      0.78      0.88         9
           6       1.00      0.91      0.95        53
           7       0.94      0.87      0.90        38
           8       0.90      0.82      0.86        44

    accuracy                           0.96      1097
   macro avg       0.96      

###### Support Vector Classification OneVsRestClassifier bag of word

In [10]:
logistic_regression_bag_word_pipeline = Pipeline([('bagOfWord', CountVectorizer(stop_words=stopwords.words('english'), ngram_range=(1, 1))),
                       ('nb_model', OneVsRestClassifier(LogisticRegression(C=10)))])

In [11]:
logistic_regression_bag_word_pipeline.fit(X_train.values, y_train.values)

Pipeline(memory=None,
         steps=[('bagOfWord',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=['i', 'me', 'my', 'myself', 'we',
                                             'our', 'ours', 'ourselves', 'you',
                                             "you're", "you've", "you...
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb_model',
                 OneVsRestClassifier(estimator=LogisticRegression(C=10,
                                                                  cl

In [12]:
logistic_regression_bag_word_prediction_result = logistic_regression_bag_word_pipeline.predict(X_val.values)

In [13]:
print('accuracy: ', accuracy_score(y_val.values, logistic_regression_bag_word_prediction_result))
print("f1 Score weighted : ",f1_score(y_val.values, logistic_regression_bag_word_prediction_result, average='weighted'))
print("f1 Score micro : ",f1_score(y_val.values, logistic_regression_bag_word_prediction_result, average='micro'))
print("f1 Score macro : ",f1_score(y_val.values, logistic_regression_bag_word_prediction_result, average='macro'))
print('confusion matrices: ')
print(multilabel_confusion_matrix(y_val.values, logistic_regression_bag_word_prediction_result))
print('classification_report: ')
print(classification_report(y_val.values, logistic_regression_bag_word_prediction_result))

accuracy:  0.9644484958979034
f1 Score weighted :  0.9640874691947594
f1 Score micro :  0.9644484958979034
f1 Score macro :  0.9326332887119126
confusion matrices: 
[[[ 533    8]
  [  10  546]]

 [[ 754   20]
  [   4  319]]

 [[1041    2]
  [   2   52]]

 [[1077    0]
  [   2   18]]

 [[1088    0]
  [   1    8]]

 [[1043    1]
  [   9   44]]

 [[1054    5]
  [   4   34]]

 [[1050    3]
  [   7   37]]]
classification_report: 
              precision    recall  f1-score   support

           1       0.99      0.98      0.98       556
           2       0.94      0.99      0.96       323
           3       0.96      0.96      0.96        54
           4       1.00      0.90      0.95        20
           5       1.00      0.89      0.94         9
           6       0.98      0.83      0.90        53
           7       0.87      0.89      0.88        38
           8       0.93      0.84      0.88        44

    accuracy                           0.96      1097
   macro avg       0.96      

In [ ]:
# Correlation and Regression Lines - A Quick Recap #1

In [ ]:
#### Subject

In [ ]:
<img src="./HackerRankFile/CorrelationAndRegressionLines.png" alt="Correlation And Regression Lines" style="height: 900px; width:900px;"/>

In [ ]:
#### Solution

In [ ]:
to do

In [ ]:
# Correlation and Regression Lines - A Quick Recap #1

In [ ]:
#### Subject

In [ ]:
<img src="./HackerRankFile/CorrelationAndRegressionLines.png" alt="Correlation And Regression Lines" style="height: 900px; width:900px;"/>

In [ ]:
#### Solution

In [ ]:
to do

# To delete

In [46]:
input_data_all = """73  72  76
48  67  76
95  92  95
95  95  96
33  59  79
47  58  74
98  95  97
91  94  97
95  84  90
93  83  90
70  70  78
85  79  91
33  67  76
47  73  90
95  87  95
84  86  95
43  63  75
95  92  100
54  80  87
72  76  90"""
input_data_all = input_data_all.split("\n")
input_data_all

M = []
P = []
C = []
for one_element in input_data_all:
    split_element = one_element.split(" ")
    M.append(int(split_element[0]))
    P.append(int(split_element[2]))
    C.append(int(split_element[4]))
    
    
import math

def mean_list(list_to_mean):
    """
    """
    return sum(list_to_mean)/len(list_to_mean)

def different_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]-second_vector[one_values])
    return result_diff


def product_between_two_vector(first_vector, second_vector):
    """
    """
    result_diff = []
    
    for one_values in range(len(first_vector)):
        result_diff.append(first_vector[one_values]*second_vector[one_values])
    return result_diff

    
def compute_coef_regression(X, Y):
    """
        Y = A+BX
    """
    
    mean_x = mean_list(X)
    mean_y = mean_list(Y)
    
    cov_X_Y = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(Y, len(Y)*[mean_y])))
    var_X = sum(product_between_two_vector(different_between_two_vector(X, len(X)*[mean_x]), different_between_two_vector(X, len(X)*[mean_x])))
    var_Y = sum(product_between_two_vector(different_between_two_vector(Y, len(Y)*[mean_y]), different_between_two_vector(Y, len(X)*[mean_y])))
    return cov_X_Y/math.sqrt(var_X*var_Y)


print('%.2f' % round(compute_coef_regression(M, P),2))
print('%.2f' % round(compute_coef_regression(P, C),2))
print('%.2f' % round(compute_coef_regression(M, C),2))

0.89
0.92
0.81


0.89
0.92
0.81


In [21]:
val_x = (9 * 7 + 107) / 20

In [22]:
val_x

8.5

In [25]:
print(round((107+9*7)/20,1))

8.5


In [20]:
ans

15.458333333333332